---
abstract: 'RT TakeScreenshots Extension'
author:
  - 'Thomas Sibley C<< <trs@bestpractical.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-TakeScreenshots
no_index:
  directory:
    - etc
    - inc
recommends:
  Alien::SeleniumRC: 0
requires:
  Path::Class: 0
  WWW::Selenium: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
